/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EduDAO__factory } from './EduDAO__factory.js';
export { IEduBadge__factory } from './IEduBadge__factory.js';