/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'EduBadge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EduBadge__factory>
getContractFactory(name: 'EduDAO', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EduDAO__factory>
getContractFactory(name: 'IEduBadge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEduBadge__factory>
getContractFactory(name: 'EduStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EduStaking__factory>
getContractFactory(name: 'IEduBadge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEduBadge__factory>
getContractFactory(name: 'IEduToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEduToken__factory>
getContractFactory(name: 'EduToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EduToken__factory>

  getContractAt(name: 'EduBadge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EduBadge>
getContractAt(name: 'EduDAO', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EduDAO>
getContractAt(name: 'IEduBadge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEduBadge>
getContractAt(name: 'EduStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EduStaking>
getContractAt(name: 'IEduBadge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEduBadge>
getContractAt(name: 'IEduToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEduToken>
getContractAt(name: 'EduToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EduToken>

  deployContract(name: 'EduBadge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduBadge>
deployContract(name: 'EduDAO', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduDAO>
deployContract(name: 'IEduBadge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEduBadge>
deployContract(name: 'EduStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduStaking>
deployContract(name: 'IEduBadge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEduBadge>
deployContract(name: 'IEduToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEduToken>
deployContract(name: 'EduToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduToken>

  deployContract(name: 'EduBadge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduBadge>
deployContract(name: 'EduDAO', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduDAO>
deployContract(name: 'IEduBadge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEduBadge>
deployContract(name: 'EduStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduStaking>
deployContract(name: 'IEduBadge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEduBadge>
deployContract(name: 'IEduToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEduToken>
deployContract(name: 'EduToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  