/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eduDaoSol from './EduDAO.sol/index.js';
export type { eduDaoSol };
import type * as eduStakingSol from './EduStaking.sol/index.js';
export type { eduStakingSol };
export type { EduBadge } from './EduBadge.js';
export type { EduToken } from './EduToken.js';
export * as factories from './factories/index.js';
export { EduBadge__factory } from './factories/EduBadge__factory.js';
export type { EduDAO } from './EduDAO.sol/EduDAO.js';
export { EduDAO__factory } from './factories/EduDAO.sol/EduDAO__factory.js';
export type { IEduBadge } from './EduDAO.sol/IEduBadge.js';
export { IEduBadge__factory } from './factories/EduDAO.sol/IEduBadge__factory.js';
export type { EduStaking } from './EduStaking.sol/EduStaking.js';
export { EduStaking__factory } from './factories/EduStaking.sol/EduStaking__factory.js';
export type { IEduToken } from './EduStaking.sol/IEduToken.js';
export { IEduToken__factory } from './factories/EduStaking.sol/IEduToken__factory.js';
export { EduToken__factory } from './factories/EduToken__factory.js';