/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as eduDaoSol from './EduDAO.sol/index.js';
export * as eduStakingSol from './EduStaking.sol/index.js';
export { EduBadge__factory } from './EduBadge__factory.js';
export { EduToken__factory } from './EduToken__factory.js';