/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EduStakingInterface extends Interface {
    getFunction(nameOrSignature: "badgeNFT" | "calculateReward" | "claimReward" | "getLatestEthPrice" | "hasStaked" | "lastStakeTime" | "priceFeed" | "stake" | "stakingBalance" | "stakingToken"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'badgeNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'calculateReward', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimReward', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLatestEthPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasStaked', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastStakeTime', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'priceFeed', values?: undefined): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stakingToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'badgeNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestEthPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasStaked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastStakeTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingToken', data: BytesLike): Result;
  }

  

  export interface EduStaking extends BaseContract {
    
    connect(runner?: ContractRunner | null): EduStaking;
    waitForDeployment(): Promise<this>;

    interface: EduStakingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    badgeNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    calculateReward: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    claimReward: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getLatestEthPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hasStaked: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lastStakeTime: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    priceFeed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakingBalance: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    stakingToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'badgeNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'calculateReward'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimReward'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getLatestEthPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasStaked'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastStakeTime'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'priceFeed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingBalance'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stakingToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }