/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EduStaking } from './EduStaking.js';
export type { IEduBadge } from './IEduBadge.js';
export type { IEduToken } from './IEduToken.js';