/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEduBadge, IEduBadgeInterface } from "../../EduStaking.sol/IEduBadge.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "safeMint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEduBadge__factory {
    static readonly abi = _abi;
    static createInterface(): IEduBadgeInterface {
      return new Interface(_abi) as IEduBadgeInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEduBadge {
      return new Contract(address, _abi, runner) as unknown as IEduBadge;
    }
  }
  