/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EduStaking__factory } from './EduStaking__factory.js';
export { IEduBadge__factory } from './IEduBadge__factory.js';
export { IEduToken__factory } from './IEduToken__factory.js';