/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EduDAOInterface extends Interface {
    getFunction(nameOrSignature: "badgeNFT" | "createProposal" | "nextProposalId" | "proposals" | "vote"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'badgeNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'createProposal', values: [string]): string;
encodeFunctionData(functionFragment: 'nextProposalId', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'badgeNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProposalId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  

  export interface EduDAO extends BaseContract {
    
    connect(runner?: ContractRunner | null): EduDAO;
    waitForDeployment(): Promise<this>;

    interface: EduDAOInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    badgeNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createProposal: TypedContractMethod<
      [_description: string, ],
      [void],
      'nonpayable'
    >
    

    
    nextProposalId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean] & {description: string, votesFor: bigint, votesAgainst: bigint, executed: boolean }],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [_proposalId: BigNumberish, _support: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'badgeNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createProposal'): TypedContractMethod<
      [_description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextProposalId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean] & {description: string, votesFor: bigint, votesAgainst: bigint, executed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_proposalId: BigNumberish, _support: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }